title: Sungmin's journey
email: smoh2044@gmail.com
description: >-  # this means to ignore newlines until next conf
  Developer who is interested in recommendation system, personalization, etc.
# permalink: ':title/'
baseurl: ""  # the subpath of your site, e.g. /blog
# url: "https://sungminoh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Sungmin  # add your name
author-img: author.png  # add your photo
about-author: >-
  Developer who is interested in recommendation system, personalization, etc.
# social-twitter: smoh2044
# social-facebook: sungmin.oh.984
social-github: sungminoh
social-linkedin: sungminoh
social-email: smoh2044@gmail.com

# Disqus
disqus:
  shortname: true

# Tracker
google_analytics: UA-121996471-1

# Build settings
plugins:
  - jekyll-feed
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

markdown: kramdown

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

# Pagination
paginate: 6
paginate_path: "/posts/page/:num"

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "main"
      icon: "fa-dot-circle"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      author: "Sungmin"
      permalink: ':categories/:title/'

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
