title: Sungmin's journey
email: smoh2044@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Developer who is interested in recommendation system, personalization, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sungminoh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: smoh2044
github_username: sungminoh
disqus:
  shortname: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-last-modified-at
  - jekyll-paginate

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

paginate: 5
paginate_path: "/posts/page/:num/"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "Sungmin"



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
